export type Language = "en" | "fr" | "es" | "de";

export const LANGUAGES: { code: Language; label: string }[] = [
  { code: "en", label: "EN" },
  { code: "fr", label: "FR" },
  { code: "es", label: "ES" },
  { code: "de", label: "DE" },
];

const STORAGE_KEY = "intent-lang";
const DEFAULT_LANG: Language = "en";
const VALID_LANGS: Language[] = ["en", "fr", "es", "de"];

export function getStoredLanguage(): Language {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored && VALID_LANGS.includes(stored as Language)) {
      return stored as Language;
    }
  } catch {
    // localStorage not available
  }
  return DEFAULT_LANG;
}

export function setStoredLanguage(lang: Language): void {
  try {
    localStorage.setItem(STORAGE_KEY, lang);
  } catch {
    // localStorage not available
  }
}

export function detectBrowserLanguage(): Language {
  try {
    const browserLang = navigator.language.slice(0, 2).toLowerCase();
    if (VALID_LANGS.includes(browserLang as Language)) {
      return browserLang as Language;
    }
  } catch {
    // navigator not available
  }
  return DEFAULT_LANG;
}

export function initLanguage(): Language {
  const stored = getStoredLanguage();
  if (stored !== DEFAULT_LANG) {
    return stored;
  }
  // First visit: check if there's already something stored
  const existing = localStorage.getItem(STORAGE_KEY);
  if (!existing) {
    // First visit: detect from browser
    const detected = detectBrowserLanguage();
    setStoredLanguage(detected);
    return detected;
  }
  return DEFAULT_LANG;
}

// All translations for the app
export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Landing page
    features: "Features",
    howItWorks: "How it works",
    demo: "Demo",
    login: "Login with GitHub",
    logout: "Logout",
    openSource: "Open Source",
    heroTitle1: "Code Review,",
    heroTitle2: "Reimagined",
    heroSubtitle: "Stop reviewing diffs. Start understanding changes. Intent shows you the 'why' behind every line of code.",
    inputPlaceholder: "Paste a GitHub URL (PR, repo, or comparison)",
    viewIntents: "View Intents",
    orLocalMode: "or use",
    localMode: "Local Mode",
    tryExample: "Try an example:",
    fastSetup: "Fast Setup",
    gitNative: "Git Native",
    multilingual: "Multilingual",
    aiReady: "AI-Ready",
    problemTitle: "The Problem with Code Review",
    problemSubtitle: "Traditional code review is broken. Here's why.",
    problem1Title: "Context is Missing",
    problem1Desc: "Reviewers see what changed, but never why. They spend hours reverse-engineering intent from cryptic commit messages.",
    problem2Title: "Documentation is Separate",
    problem2Desc: "Design docs live in Notion. Discussions happen in Slack. Code reviews are on GitHub. Knowledge is scattered everywhere.",
    problem3Title: "Onboarding is Painful",
    problem3Desc: "New team members can't understand why code exists. git blame gives you who and when, never why.",
    solutionBadge: "The Solution",
    solutionTitle: "Intent: Documentation that Lives with Code",
    solutionDesc: "Intent files are structured explanations stored alongside your code. They describe the 'why' behind changes using semantic anchors that survive refactoring.",
    solutionCheck1: "Chunks: Group related changes with context",
    solutionCheck2: "Decisions: Document the rationale behind choices",
    solutionCheck3: "Semantic Anchors: Links that survive refactoring",
    solutionCheck4: "Multilingual: Native support for FR, EN, ES, DE",
    featuresTitle: "Three Ways to Review",
    featuresSubtitle: "Choose the view that fits your workflow",
    compareMode: "Compare Mode",
    compareModeDesc: "Side-by-side diff view with intent cards aligned to the code they describe. Perfect for PR reviews.",
    browseMode: "Browse Mode",
    browseModeDesc: "Explore a single branch with full file content and all intents visible. Great for understanding a codebase.",
    storyMode: "Story Mode",
    storyModeDesc: "Read intents as chapters without code. Perfect for understanding the narrative of a project's evolution.",
    howItWorksTitle: "How It Works",
    howItWorksSubtitle: "Simple setup, powerful results",
    step1Title: "Create Intent Files",
    step1Desc: "Add a .intent/ folder to your repo. Write markdown files describing your changes with semantic anchors.",
    step2Title: "Link to Code",
    step2Desc: "Use @function:name, @class:Name, or @pattern:text to anchor explanations to code locations that survive refactoring.",
    step3Title: "Review with Context",
    step3Desc: "Open Intent to see diffs alongside their explanations. Intent cards appear right next to the code they describe.",
    demoTitle: "See Intent in Action",
    demoSubtitle: "A real example of intent-based code review",
    demoExplore: "Explore Intent on its own repo:",
    footerTagline: "Code review, reimagined.",
    builtWith: "Built with Claude",
    urlError: "Unrecognized URL format",

    // App - general
    new: "New",
    existing: "Existing",
    context: "CONTEXT",
    notInDiff: "not in diff",
    summary: "Summary:",
    motivation: "Motivation:",
    files: "Files:",
    documentedFiles: "Documented files",
    modifiedFiles: "Modified files",
    warning: "Warning:",
    staleWarning: "Some chunks have been modified since last update.",
    obsoleteWarning: "Some chunks reference code that no longer exists.",
    modified: "Modified",
    obsolete: "Obsolete",
    stale: "Stale",
    noChanges: "No changes found",
    selectRepo: "Select a repository",
    loading: "Loading...",
    loadingDiff: "Loading diff...",
    loadingBrowse: "Loading code...",
    loadingStory: "Loading story...",
    loadingPR: "Loading Pull Request...",
    loadingBranches: "Comparing branches...",
    loadingGitHubBrowse: "Loading repository...",
    errorTitle: "Something went wrong",
    errorMessage: "We couldn't load the data. This might be a network issue or the repository may not be accessible.",
    retry: "Try again",
    objective: "Objective:",
    risk: "Risk:",
    viewDiff: "Diff",
    viewBrowse: "Browse",
    deepDive: "Ask Claude",
    toastCopied: "Context copied! Paste it into Claude Code or claude.ai to explore this chunk.",
    toastError: "Error copying to clipboard",
    promptTitle: "Exploratory Parenthesis",
    promptDisclaimer: "This is a parenthesis to better understand a piece of code. This is NOT a new task.\nAfter this exploration, we'll resume where we left off.",
    promptContext: "Context",
    promptFile: "File",
    promptIntent: "Intent",
    promptChunkToExplore: "Chunk to explore",
    promptAnchor: "Anchor",
    promptTitleLabel: "Title",
    promptDescription: "Description",
    promptDecisions: "Decisions",
    promptSourceCode: "Source code",
    promptLines: "lines",
    promptCodeNotAvailable: "Code not available",
    promptQuestion: "My question",
    promptQuestionPlaceholder: "[Explain why this code is structured this way / What alternatives could have been used / I don't understand part X]",
    deepDiveTooltip: "Copy context to explore this chunk with Claude",
    exitStoryMode: "Exit Story Mode",
    chapter: "Chapter",
    noIntentsForStory: "No intents to display in story mode",
    showIntentFiles: "Show .intent",
    hideIntentFiles: "Hide .intent",
    expandAll: "Expand all folders",
    collapseAll: "Collapse all folders",
    noIntentTitle: "No intent documentation for this PR",
    noIntentDesc: "This PR doesn't have intent documentation yet. Intents help reviewers understand the 'why' behind code changes.",
    noIntentHint: "Intents are recommended for features, refactoring, and complex bug fixes. Small fixes and dependency updates usually don't need them.",
    createIntent: "Learn how to create intents",
    authRequired: "Authentication Required",
    authRequiredDesc: "This repository may be private. Please login with GitHub to access it.",
    binaryFileAdded: "Binary file added",
    binaryFileDeleted: "Binary file deleted",
    binaryFileModified: "Binary file modified",
    fileAdded: "File added",
    fileDeleted: "File deleted",
    fileModified: "File modified",
    // Project overview
    projectOverview: "Project Overview",
    intentsCount: "intents",
    filesDocumented: "files documented",
    viewStoryMode: "View as Story",
    backToCode: "Back to Code",
    stars: "stars",
    primaryLanguage: "Primary Language",
    topics: "Topics",
    uniqueTags: "Tags",
    riskOverview: "Risk Levels",
    lowRisk: "low",
    mediumRisk: "medium",
    highRisk: "high",
    activeIntents: "active",
    archivedIntents: "archived",
    recentUpdates: "Recent Updates",
    noDescription: "No description available",
  },
  fr: {
    // Landing page
    features: "Fonctionnalites",
    howItWorks: "Comment ca marche",
    demo: "Demo",
    login: "Se connecter avec GitHub",
    logout: "Deconnexion",
    openSource: "Open Source",
    heroTitle1: "Revue de code,",
    heroTitle2: "Reinventee",
    heroSubtitle: "Arretez de relire des diffs. Commencez a comprendre les changements. Intent vous montre le 'pourquoi' derriere chaque ligne de code.",
    inputPlaceholder: "Collez une URL GitHub (PR, repo, ou comparaison)",
    viewIntents: "Voir les Intents",
    orLocalMode: "ou utilisez le",
    localMode: "Mode Local",
    tryExample: "Essayez un exemple:",
    fastSetup: "Config Rapide",
    gitNative: "Git Natif",
    multilingual: "Multilingue",
    aiReady: "Pret pour l'IA",
    problemTitle: "Le Probleme avec la Revue de Code",
    problemSubtitle: "La revue de code traditionnelle est cassee. Voici pourquoi.",
    problem1Title: "Le Contexte Manque",
    problem1Desc: "Les reviewers voient ce qui a change, mais jamais pourquoi. Ils passent des heures a deviner l'intention a partir de messages de commit cryptiques.",
    problem2Title: "La Documentation est Separee",
    problem2Desc: "Les docs de design sont sur Notion. Les discussions sur Slack. Les reviews sur GitHub. La connaissance est eparpillee partout.",
    problem3Title: "L'Onboarding est Douloureux",
    problem3Desc: "Les nouveaux membres ne comprennent pas pourquoi le code existe. git blame donne le qui et le quand, jamais le pourquoi.",
    solutionBadge: "La Solution",
    solutionTitle: "Intent : Documentation qui Vit avec le Code",
    solutionDesc: "Les fichiers Intent sont des explications structurees stockees a cote de votre code. Ils decrivent le 'pourquoi' des changements avec des ancres semantiques qui resistent au refactoring.",
    solutionCheck1: "Chunks : Regroupez les changements avec leur contexte",
    solutionCheck2: "Decisions : Documentez le raisonnement derriere les choix",
    solutionCheck3: "Ancres Semantiques : Liens qui resistent au refactoring",
    solutionCheck4: "Multilingue : Support natif FR, EN, ES, DE",
    featuresTitle: "Trois Facons de Relire",
    featuresSubtitle: "Choisissez la vue qui correspond a votre workflow",
    compareMode: "Mode Compare",
    compareModeDesc: "Vue diff cote a cote avec les cartes d'intent alignees sur le code qu'elles decrivent. Parfait pour les PR reviews.",
    browseMode: "Mode Browse",
    browseModeDesc: "Explorez une branche avec le contenu complet des fichiers et tous les intents visibles. Ideal pour comprendre une codebase.",
    storyMode: "Mode Recit",
    storyModeDesc: "Lisez les intents comme des chapitres sans code. Parfait pour comprendre l'evolution narrative d'un projet.",
    howItWorksTitle: "Comment Ca Marche",
    howItWorksSubtitle: "Configuration simple, resultats puissants",
    step1Title: "Creez des Fichiers Intent",
    step1Desc: "Ajoutez un dossier .intent/ a votre repo. Ecrivez des fichiers markdown decrivant vos changements avec des ancres semantiques.",
    step2Title: "Liez au Code",
    step2Desc: "Utilisez @function:name, @class:Name, ou @pattern:text pour ancrer les explications a des emplacements de code qui resistent au refactoring.",
    step3Title: "Revoyez avec Contexte",
    step3Desc: "Ouvrez Intent pour voir les diffs a cote de leurs explications. Les cartes d'intent apparaissent juste a cote du code qu'elles decrivent.",
    demoTitle: "Voyez Intent en Action",
    demoSubtitle: "Un vrai exemple de revue de code basee sur les intents",
    demoExplore: "Explorez Intent sur son propre repo:",
    footerTagline: "Revue de code, reinventee.",
    builtWith: "Construit avec Claude",
    urlError: "Format d'URL non reconnu",

    // App - general
    new: "Nouveau",
    existing: "Existant",
    context: "CONTEXTE",
    notInDiff: "hors diff",
    summary: "Resume:",
    motivation: "Motivation:",
    files: "Fichiers:",
    documentedFiles: "Fichiers documentes",
    modifiedFiles: "Fichiers modifies",
    warning: "Attention:",
    staleWarning: "Certains chunks ont ete modifies depuis la derniere mise a jour.",
    obsoleteWarning: "Certains chunks referencent du code qui n'existe plus.",
    obsolete: "Obsolete",
    stale: "Modifie",
    modified: "Modifie",
    noChanges: "Aucun changement trouve",
    selectRepo: "Selectionner un depot",
    loading: "Chargement...",
    loadingDiff: "Chargement du diff...",
    loadingBrowse: "Chargement du code...",
    loadingStory: "Chargement du recit...",
    loadingPR: "Chargement de la Pull Request...",
    loadingBranches: "Comparaison des branches...",
    loadingGitHubBrowse: "Chargement du depot...",
    errorTitle: "Une erreur est survenue",
    errorMessage: "Impossible de charger les donnees. Cela peut etre un probleme reseau ou le depot n'est pas accessible.",
    retry: "Reessayer",
    objective: "Objectif:",
    risk: "Risque:",
    viewDiff: "Diff",
    viewBrowse: "Parcourir",
    deepDive: "Demander a Claude",
    toastCopied: "Contexte copie ! Colle-le dans Claude Code ou claude.ai pour explorer ce chunk.",
    toastError: "Erreur lors de la copie",
    promptTitle: "Parenthese exploratoire",
    promptDisclaimer: "Ceci est une parenthese pour mieux comprendre un morceau de code. Ce n'est PAS une nouvelle tache.\nApres cette exploration, on reprendra la ou on en etait.",
    promptContext: "Contexte",
    promptFile: "Fichier",
    promptIntent: "Intent",
    promptChunkToExplore: "Chunk a explorer",
    promptAnchor: "Ancre",
    promptTitleLabel: "Titre",
    promptDescription: "Description",
    promptDecisions: "Decisions",
    promptSourceCode: "Code source",
    promptLines: "lignes",
    promptCodeNotAvailable: "Code non disponible",
    promptQuestion: "Ma question",
    promptQuestionPlaceholder: "[Explique-moi pourquoi ce code est structure ainsi / Quelles alternatives auraient ete possibles / Je ne comprends pas la partie X]",
    deepDiveTooltip: "Copier le contexte pour explorer ce chunk avec Claude",
    exitStoryMode: "Quitter le mode recit",
    chapter: "Chapitre",
    noIntentsForStory: "Aucun intent a afficher en mode recit",
    showIntentFiles: "Afficher .intent",
    hideIntentFiles: "Masquer .intent",
    expandAll: "Deplier tous les dossiers",
    collapseAll: "Replier tous les dossiers",
    noIntentTitle: "Pas de documentation intent pour cette PR",
    noIntentDesc: "Cette PR n'a pas encore de documentation intent. Les intents aident les reviewers a comprendre le 'pourquoi' des changements.",
    noIntentHint: "Les intents sont recommandes pour les features, refactoring et bugs complexes. Les petits fixes et mises a jour de dependances n'en ont generalement pas besoin.",
    createIntent: "Apprendre a creer des intents",
    authRequired: "Authentification requise",
    authRequiredDesc: "Ce depot est peut-etre prive. Veuillez vous connecter avec GitHub pour y acceder.",
    binaryFileAdded: "Fichier binaire ajoute",
    binaryFileDeleted: "Fichier binaire supprime",
    binaryFileModified: "Fichier binaire modifie",
    fileAdded: "Fichier ajoute",
    fileDeleted: "Fichier supprime",
    fileModified: "Fichier modifie",
    // Project overview
    projectOverview: "Apercu du Projet",
    intentsCount: "intents",
    filesDocumented: "fichiers documentes",
    viewStoryMode: "Voir en mode recit",
    backToCode: "Retour au code",
    stars: "etoiles",
    primaryLanguage: "Langage Principal",
    topics: "Sujets",
    uniqueTags: "Tags",
    riskOverview: "Niveaux de Risque",
    lowRisk: "faible",
    mediumRisk: "moyen",
    highRisk: "eleve",
    activeIntents: "actifs",
    archivedIntents: "archives",
    recentUpdates: "Mises a jour recentes",
    noDescription: "Aucune description disponible",
  },
  es: {
    // Landing page
    features: "Caracteristicas",
    howItWorks: "Como funciona",
    demo: "Demo",
    login: "Iniciar sesion con GitHub",
    logout: "Cerrar sesion",
    openSource: "Codigo Abierto",
    heroTitle1: "Revision de codigo,",
    heroTitle2: "Reinventada",
    heroSubtitle: "Deja de revisar diffs. Empieza a entender los cambios. Intent te muestra el 'por que' detras de cada linea de codigo.",
    inputPlaceholder: "Pega una URL de GitHub (PR, repo, o comparacion)",
    viewIntents: "Ver Intents",
    orLocalMode: "o usa el",
    localMode: "Modo Local",
    tryExample: "Prueba un ejemplo:",
    fastSetup: "Configuracion Rapida",
    gitNative: "Git Nativo",
    multilingual: "Multilingue",
    aiReady: "Listo para IA",
    problemTitle: "El Problema con la Revision de Codigo",
    problemSubtitle: "La revision de codigo tradicional esta rota. He aqui por que.",
    problem1Title: "Falta el Contexto",
    problem1Desc: "Los revisores ven que cambio, pero nunca por que. Pasan horas descifrando la intencion de mensajes de commit cripticos.",
    problem2Title: "La Documentacion esta Separada",
    problem2Desc: "Los docs de diseno estan en Notion. Las discusiones en Slack. Las revisiones en GitHub. El conocimiento esta disperso.",
    problem3Title: "La Incorporacion es Dolorosa",
    problem3Desc: "Los nuevos miembros no entienden por que existe el codigo. git blame da el quien y el cuando, nunca el por que.",
    solutionBadge: "La Solucion",
    solutionTitle: "Intent: Documentacion que Vive con el Codigo",
    solutionDesc: "Los archivos Intent son explicaciones estructuradas almacenadas junto a tu codigo. Describen el 'por que' de los cambios usando anclas semanticas que sobreviven al refactoring.",
    solutionCheck1: "Chunks: Agrupa cambios relacionados con contexto",
    solutionCheck2: "Decisiones: Documenta el razonamiento detras de las elecciones",
    solutionCheck3: "Anclas Semanticas: Enlaces que sobreviven al refactoring",
    solutionCheck4: "Multilingue: Soporte nativo para FR, EN, ES, DE",
    featuresTitle: "Tres Formas de Revisar",
    featuresSubtitle: "Elige la vista que se adapte a tu flujo de trabajo",
    compareMode: "Modo Comparar",
    compareModeDesc: "Vista diff lado a lado con tarjetas intent alineadas al codigo que describen. Perfecto para revisiones de PR.",
    browseMode: "Modo Explorar",
    browseModeDesc: "Explora una rama con todo el contenido de archivos e intents visibles. Ideal para entender un codebase.",
    storyMode: "Modo Historia",
    storyModeDesc: "Lee intents como capitulos sin codigo. Perfecto para entender la narrativa de la evolucion de un proyecto.",
    howItWorksTitle: "Como Funciona",
    howItWorksSubtitle: "Configuracion simple, resultados potentes",
    step1Title: "Crea Archivos Intent",
    step1Desc: "Anade una carpeta .intent/ a tu repo. Escribe archivos markdown describiendo tus cambios con anclas semanticas.",
    step2Title: "Enlaza al Codigo",
    step2Desc: "Usa @function:name, @class:Name, o @pattern:text para anclar explicaciones a ubicaciones de codigo que sobreviven al refactoring.",
    step3Title: "Revisa con Contexto",
    step3Desc: "Abre Intent para ver diffs junto a sus explicaciones. Las tarjetas intent aparecen justo al lado del codigo que describen.",
    demoTitle: "Ve Intent en Accion",
    demoSubtitle: "Un ejemplo real de revision de codigo basada en intents",
    demoExplore: "Explora Intent en su propio repo:",
    footerTagline: "Revision de codigo, reinventada.",
    builtWith: "Construido con Claude",
    urlError: "Formato de URL no reconocido",

    // App - general
    new: "Nuevo",
    existing: "Existente",
    context: "CONTEXTO",
    notInDiff: "fuera del diff",
    summary: "Resumen:",
    motivation: "Motivacion:",
    files: "Archivos:",
    documentedFiles: "Archivos documentados",
    modifiedFiles: "Archivos modificados",
    warning: "Atencion:",
    staleWarning: "Algunos chunks han sido modificados desde la ultima actualizacion.",
    obsoleteWarning: "Algunos chunks referencian codigo que ya no existe.",
    modified: "Modificado",
    obsolete: "Obsoleto",
    stale: "Modificado",
    noChanges: "No se encontraron cambios",
    selectRepo: "Seleccionar repositorio",
    loading: "Cargando...",
    loadingDiff: "Cargando diff...",
    loadingBrowse: "Cargando codigo...",
    loadingStory: "Cargando historia...",
    loadingPR: "Cargando Pull Request...",
    loadingBranches: "Comparando ramas...",
    loadingGitHubBrowse: "Cargando repositorio...",
    errorTitle: "Algo salio mal",
    errorMessage: "No pudimos cargar los datos. Puede ser un problema de red o el repositorio no es accesible.",
    retry: "Reintentar",
    objective: "Objetivo:",
    risk: "Riesgo:",
    viewDiff: "Diff",
    viewBrowse: "Explorar",
    deepDive: "Preguntar a Claude",
    toastCopied: "Contexto copiado! Pegalo en Claude Code o claude.ai para explorar este chunk.",
    toastError: "Error al copiar",
    promptTitle: "Parentesis exploratorio",
    promptDisclaimer: "Este es un parentesis para entender mejor un fragmento de codigo. NO es una tarea nueva.\nDespues de esta exploracion, retomaremos donde lo dejamos.",
    promptContext: "Contexto",
    promptFile: "Archivo",
    promptIntent: "Intent",
    promptChunkToExplore: "Chunk a explorar",
    promptAnchor: "Ancla",
    promptTitleLabel: "Titulo",
    promptDescription: "Descripcion",
    promptDecisions: "Decisiones",
    promptSourceCode: "Codigo fuente",
    promptLines: "lineas",
    promptCodeNotAvailable: "Codigo no disponible",
    promptQuestion: "Mi pregunta",
    promptQuestionPlaceholder: "[Explicame por que este codigo esta estructurado asi / Que alternativas se podrian haber usado / No entiendo la parte X]",
    deepDiveTooltip: "Copiar contexto para explorar este chunk con Claude",
    exitStoryMode: "Salir del modo historia",
    chapter: "Capitulo",
    noIntentsForStory: "No hay intents para mostrar en modo historia",
    showIntentFiles: "Mostrar .intent",
    hideIntentFiles: "Ocultar .intent",
    expandAll: "Expandir todas las carpetas",
    collapseAll: "Colapsar todas las carpetas",
    noIntentTitle: "Sin documentacion intent para esta PR",
    noIntentDesc: "Esta PR aun no tiene documentacion intent. Los intents ayudan a los revisores a entender el 'por que' de los cambios.",
    noIntentHint: "Los intents se recomiendan para features, refactoring y bugs complejos. Los pequenos fixes y actualizaciones de dependencias generalmente no los necesitan.",
    createIntent: "Aprende a crear intents",
    authRequired: "Autenticacion requerida",
    authRequiredDesc: "Este repositorio puede ser privado. Por favor inicia sesion con GitHub para acceder.",
    binaryFileAdded: "Archivo binario anadido",
    binaryFileDeleted: "Archivo binario eliminado",
    binaryFileModified: "Archivo binario modificado",
    fileAdded: "Archivo anadido",
    fileDeleted: "Archivo eliminado",
    fileModified: "Archivo modificado",
    // Project overview
    projectOverview: "Vision General del Proyecto",
    intentsCount: "intents",
    filesDocumented: "archivos documentados",
    viewStoryMode: "Ver como historia",
    backToCode: "Volver al codigo",
    stars: "estrellas",
    primaryLanguage: "Lenguaje Principal",
    topics: "Temas",
    uniqueTags: "Etiquetas",
    riskOverview: "Niveles de Riesgo",
    lowRisk: "bajo",
    mediumRisk: "medio",
    highRisk: "alto",
    activeIntents: "activos",
    archivedIntents: "archivados",
    recentUpdates: "Actualizaciones Recientes",
    noDescription: "Sin descripcion disponible",
  },
  de: {
    // Landing page
    features: "Funktionen",
    howItWorks: "Wie es funktioniert",
    demo: "Demo",
    login: "Mit GitHub anmelden",
    logout: "Abmelden",
    openSource: "Open Source",
    heroTitle1: "Code Review,",
    heroTitle2: "Neu gedacht",
    heroSubtitle: "Horen Sie auf, Diffs zu lesen. Verstehen Sie Anderungen. Intent zeigt Ihnen das 'Warum' hinter jeder Codezeile.",
    inputPlaceholder: "GitHub URL einfugen (PR, Repo oder Vergleich)",
    viewIntents: "Intents anzeigen",
    orLocalMode: "oder nutzen Sie den",
    localMode: "Lokalen Modus",
    tryExample: "Beispiel ausprobieren:",
    fastSetup: "Schnelle Einrichtung",
    gitNative: "Git Nativ",
    multilingual: "Mehrsprachig",
    aiReady: "KI-bereit",
    problemTitle: "Das Problem mit Code Review",
    problemSubtitle: "Traditionelles Code Review ist kaputt. Hier ist warum.",
    problem1Title: "Kontext fehlt",
    problem1Desc: "Reviewer sehen was sich geandert hat, aber nie warum. Sie verbringen Stunden damit, die Absicht aus kryptischen Commit-Nachrichten zu entschlusseln.",
    problem2Title: "Dokumentation ist getrennt",
    problem2Desc: "Design-Docs sind in Notion. Diskussionen in Slack. Reviews auf GitHub. Wissen ist uberall verstreut.",
    problem3Title: "Onboarding ist schmerzhaft",
    problem3Desc: "Neue Teammitglieder verstehen nicht, warum Code existiert. git blame gibt wer und wann, nie warum.",
    solutionBadge: "Die Losung",
    solutionTitle: "Intent: Dokumentation die mit dem Code lebt",
    solutionDesc: "Intent-Dateien sind strukturierte Erklarungen, die neben Ihrem Code gespeichert werden. Sie beschreiben das 'Warum' hinter Anderungen mit semantischen Ankern, die Refactoring uberleben.",
    solutionCheck1: "Chunks: Gruppieren Sie zusammenhangende Anderungen mit Kontext",
    solutionCheck2: "Entscheidungen: Dokumentieren Sie die Begrundung hinter Entscheidungen",
    solutionCheck3: "Semantische Anker: Links die Refactoring uberleben",
    solutionCheck4: "Mehrsprachig: Native Unterstutzung fur FR, EN, ES, DE",
    featuresTitle: "Drei Arten zu reviewen",
    featuresSubtitle: "Wahlen Sie die Ansicht die zu Ihrem Workflow passt",
    compareMode: "Vergleichsmodus",
    compareModeDesc: "Side-by-side Diff-Ansicht mit Intent-Karten ausgerichtet am Code den sie beschreiben. Perfekt fur PR-Reviews.",
    browseMode: "Durchsuchen-Modus",
    browseModeDesc: "Erkunden Sie einen Branch mit vollstandigem Dateiinhalt und allen sichtbaren Intents. Ideal um eine Codebase zu verstehen.",
    storyMode: "Story-Modus",
    storyModeDesc: "Lesen Sie Intents als Kapitel ohne Code. Perfekt um die Geschichte der Projektentwicklung zu verstehen.",
    howItWorksTitle: "Wie es funktioniert",
    howItWorksSubtitle: "Einfache Einrichtung, kraftige Ergebnisse",
    step1Title: "Intent-Dateien erstellen",
    step1Desc: "Fugen Sie einen .intent/ Ordner zu Ihrem Repo hinzu. Schreiben Sie Markdown-Dateien die Ihre Anderungen mit semantischen Ankern beschreiben.",
    step2Title: "Mit Code verlinken",
    step2Desc: "Verwenden Sie @function:name, @class:Name, oder @pattern:text um Erklarungen an Code-Stellen zu verankern die Refactoring uberleben.",
    step3Title: "Mit Kontext reviewen",
    step3Desc: "Offnen Sie Intent um Diffs neben ihren Erklarungen zu sehen. Intent-Karten erscheinen direkt neben dem Code den sie beschreiben.",
    demoTitle: "Intent in Aktion sehen",
    demoSubtitle: "Ein echtes Beispiel fur intent-basiertes Code Review",
    demoExplore: "Intent auf seinem eigenen Repo erkunden:",
    footerTagline: "Code Review, neu gedacht.",
    builtWith: "Gebaut mit Claude",
    urlError: "Nicht erkanntes URL-Format",

    // App - general
    new: "Neu",
    existing: "Bestehend",
    context: "KONTEXT",
    notInDiff: "nicht im Diff",
    summary: "Zusammenfassung:",
    motivation: "Motivation:",
    files: "Dateien:",
    documentedFiles: "Dokumentierte Dateien",
    modifiedFiles: "Geanderte Dateien",
    warning: "Achtung:",
    staleWarning: "Einige Chunks wurden seit dem letzten Update geandert.",
    obsoleteWarning: "Einige Chunks referenzieren Code der nicht mehr existiert.",
    modified: "Geandert",
    obsolete: "Veraltet",
    stale: "Veraltet",
    noChanges: "Keine Anderungen gefunden",
    selectRepo: "Repository auswahlen",
    loading: "Laden...",
    loadingDiff: "Diff wird geladen...",
    loadingBrowse: "Code wird geladen...",
    loadingStory: "Geschichte wird geladen...",
    loadingPR: "Pull Request wird geladen...",
    loadingBranches: "Branches werden verglichen...",
    loadingGitHubBrowse: "Repository wird geladen...",
    errorTitle: "Etwas ist schief gelaufen",
    errorMessage: "Die Daten konnten nicht geladen werden. Dies konnte ein Netzwerkproblem sein oder das Repository ist nicht zuganglich.",
    retry: "Erneut versuchen",
    objective: "Ziel:",
    risk: "Risiko:",
    viewDiff: "Diff",
    viewBrowse: "Durchsuchen",
    deepDive: "Claude fragen",
    toastCopied: "Kontext kopiert! Fugen Sie ihn in Claude Code oder claude.ai ein um diesen Chunk zu erkunden.",
    toastError: "Fehler beim Kopieren",
    promptTitle: "Explorative Klammer",
    promptDisclaimer: "Dies ist eine Klammer um ein Stuck Code besser zu verstehen. Dies ist KEINE neue Aufgabe.\nNach dieser Erkundung machen wir dort weiter wo wir aufgehort haben.",
    promptContext: "Kontext",
    promptFile: "Datei",
    promptIntent: "Intent",
    promptChunkToExplore: "Zu erkundender Chunk",
    promptAnchor: "Anker",
    promptTitleLabel: "Titel",
    promptDescription: "Beschreibung",
    promptDecisions: "Entscheidungen",
    promptSourceCode: "Quellcode",
    promptLines: "Zeilen",
    promptCodeNotAvailable: "Code nicht verfugbar",
    promptQuestion: "Meine Frage",
    promptQuestionPlaceholder: "[Erklare mir warum dieser Code so strukturiert ist / Welche Alternativen hatte es gegeben / Ich verstehe Teil X nicht]",
    deepDiveTooltip: "Kontext kopieren um diesen Chunk mit Claude zu erkunden",
    exitStoryMode: "Story-Modus verlassen",
    chapter: "Kapitel",
    noIntentsForStory: "Keine Intents zum Anzeigen im Story-Modus",
    showIntentFiles: ".intent anzeigen",
    hideIntentFiles: ".intent ausblenden",
    expandAll: "Alle Ordner aufklappen",
    collapseAll: "Alle Ordner zuklappen",
    noIntentTitle: "Keine Intent-Dokumentation fur diese PR",
    noIntentDesc: "Diese PR hat noch keine Intent-Dokumentation. Intents helfen Reviewern das 'Warum' hinter Code-Anderungen zu verstehen.",
    noIntentHint: "Intents werden fur Features, Refactoring und komplexe Bugfixes empfohlen. Kleine Fixes und Dependency-Updates brauchen sie normalerweise nicht.",
    createIntent: "Lernen Sie wie man Intents erstellt",
    authRequired: "Authentifizierung erforderlich",
    authRequiredDesc: "Dieses Repository ist moglicherweise privat. Bitte melden Sie sich mit GitHub an um darauf zuzugreifen.",
    binaryFileAdded: "Binardatei hinzugefugt",
    binaryFileDeleted: "Binardatei geloscht",
    binaryFileModified: "Binardatei geandert",
    fileAdded: "Datei hinzugefugt",
    fileDeleted: "Datei geloscht",
    fileModified: "Datei geandert",
    // Project overview
    projectOverview: "Projektuberblick",
    intentsCount: "Intents",
    filesDocumented: "dokumentierte Dateien",
    viewStoryMode: "Als Story anzeigen",
    backToCode: "Zuruck zum Code",
    stars: "Sterne",
    primaryLanguage: "Hauptsprache",
    topics: "Themen",
    uniqueTags: "Tags",
    riskOverview: "Risikolevel",
    lowRisk: "niedrig",
    mediumRisk: "mittel",
    highRisk: "hoch",
    activeIntents: "aktiv",
    archivedIntents: "archiviert",
    recentUpdates: "Aktuelle Updates",
    noDescription: "Keine Beschreibung verfugbar",
  },
};

// Helper to get translation with fallback to English
export function t(lang: Language, key: string): string {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
}
